#!/usr/bin/env bash
set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "${SCRIPT_DIR}"

git add -A

if ! git diff --cached --quiet; then
  git commit -m "sync obsidian $(date '+%Y-%m-%d %H:%M')"
fi

git pull --rebase --autostash
git push
